config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'contact/index'
  get 'my_work/index'
  get 'about_me/index'
  root to: "top_page#index"
  resources :new_posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_work.rb
class MyWork < ApplicationRecord
end

app/models/new_post.rb
class NewPost < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_me_controller.rb
class AboutMeController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/my_work_controller.rb
class MyWorkController < ApplicationController
  def index
    @mywork = MyWork.all
  end
end

app/controllers/new_posts_controller.rb
class NewPostsController < ApplicationController
  def new
    @post = NewPost.new
  end

  def create
    @post = NewPost.create(new_post_params)
    if @post.save
      redirect_to root_path
    end
  end

  private
  def new_post_params
    params.require(:new_post).permit(:new_post)
  end
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController
  def index
    @post = NewPost.all
  end
end

app/helpers/about_me_helper.rb
module AboutMeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/my_work_helper.rb
module MyWorkHelper
end

app/helpers/new_posts_helper.rb
module NewPostsHelper
end

app/helpers/top_page_helper.rb
module TopPageHelper
end

app/views/about_me/index.html.erb
<div class = "wrapper">
  <div class = "side_wrap">
    <%= render "shared/side_bar"%>
  </div>

  <div class = "main about_me">
    <div class = "about_me_left">
    </div>

    <div class = "about_me_right">
      <div class = "history">
        <div class = "history_tytle">経歴</div>
        <div class = "history_name">名前：猪飼航一郎 / Koichiro Ikai</div>
        <div class = "history_age">生年月日：1993年4月12日</div>
        <div class = "history_edu">最終学歴：豊橋技術科学大学大学院卒</div>
        <div class = "history_rireki">
        大学卒業後、営業として製本機械販売会社に入社。<br>
        会社のホームページを作成する機会があり、ITの業種に興味をもつ。<br>
        一社目を退社後、インフラ系のIT企業へ入社。<br>
        そこで自分が実際にやりたいのはWebアプリケーション開発であると気付き、退職。<br>
        基礎的なWebアプリケーションについて学ぶため、TechCampを受講。<br>
        TechCamp81期生として卒業し、現在Webエンジニアを目指して転職活動中。
        </div>
      </div>

      <div class = "skill">
        <div class = "histroy_tytle">Skills</div>
        <div class = "skill_book">
          <div class = "skill_category">
            英語
          </div>
          <div class = "skill_level">
            英語検定２級
          </div>
          <div class = "skill_level">
            Toeic　890点
          </div>
        </div>

        <div class = "skill_book">
          <div class = "skill_category">
            言語
          </div>
          <div class = "skill_level">
            Ruby/Rails
          </div>
        </div>

        <div class = "skill_book">
          <div class = "skill_category">
            インフラ
          </div>
          <div class = "skill_level">
            CCNA
          </div>
          <div class = "skill_level">
            AWS
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contact/index.html.erb
<div class = "wrapper">
  <div class = "side_wrap">
    <%= render "shared/side_bar"%>
  </div>

  <div class = "main contact">
    <div class = "contact_top">
      <div class = "contact_link">
        twitter
      </div>
      <div class = "contact_link">
        facebook
      </div>
      <div class = "contact_link">
        email
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/my_work/index.html.erb
<div class = "wrapper">
  <div class = "side_wrap">
    <%= render "shared/side_bar"%>
  </div>

  <div class = "main my_work">
    <div class = "work_wrapper">
      <% @mywork.each do |f| %>
        <div class = "work_colum" >
          <%= image_tag f.pic, class:"work_pic" %>
          <div class = "work_exp">
          サイト名：<%= f.site_name%><br>
          URL：<%= f.url%><br>
          github：<%= f.github%><br>
          概要：<%= f.info%><br>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_side_bar.html.erb
<%= link_to root_path, class:"side_top" do %>
    <div class = "side_title">
      Koichiro Ikai <br>
      Portfolio
      
    </div>
<% end %>

  <%= link_to about_me_index_path, class: "side_bottom" do %>
    <div class = "side_title">
      AboutMe
    </div>
  <% end %>

  <%= link_to my_work_index_path, class: "side_bottom" do %>
    <div class = "side_title">
      MyWork
    </div>
  <% end %>

  <%= link_to contact_index_path, class: "side_bottom" do %>
    <div class = "side_title">
      Contact
    </div>
  <% end %>

app/views/top_page/_side_bar.html.erb
<%= link_to root_path, class:"side_top" do %>
    <div class = "side_title">
      Koichiro Ikai <br>
      Portfolio
    </div>
<% end %>

  <%= link_to "#", class: "side_bottom" do %>
    <div class = "side_title">
      AboutMe
    </div>
  <% end %>

  <%= link_to "#", class: "side_bottom" do %>
    <div class = "side_title">
      MyWork
    </div>
  <% end %>

  <%= link_to "#", class: "side_bottom" do %>
    <div class = "side_title">
      Contact
    </div>
  <% end %>

app/views/top_page/index.html.erb
<div class = "wrapper">
  <div class = "side_wrap">
    <%= render "shared/side_bar"%>
  </div>

  <div class = "main top_page">
    <div class = "main_left">
      <div class = "welcome">
      </div>
        <p class = "top_comment">
          Welcome to my portfolio!!
        </p>
      <% if user_signed_in? %>
        編集者ログイン中
      <% end %>

    </div>
    <div class = "main_right">
      <div class = "my_twitter">
        <div class = "twitter_box">
              <a class="twitter-timeline" data-chrome=”noheader” data-width="350" href="https://twitter.com/ItAnmona?ref_src=twsrc%5Etfw">Tweets by ItAnmona</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
      </div>

      <div class = "update">
        <div class = "update_wrap">
            <p>
              更新履歴
            </p>
          <div class = "post_box">
            <% @post.each do |post| %>
              <div class = "post_colum">
                <div class = "post_info">
                  <%= post.new_post %> <br>
                </div>
                <div class = "post_date">
                  更新日<%= post.created_at %> 
                </div>
              </div>
            <% end %>
            <% if user_signed_in? == true %>
              <%= form_with model:@post,url: new_posts_path, local: true do |f| %>
                <%= f.text_field :new_post, class:"クラス", placeholder:"更新内容" %>
                <%= f.submit "更新", class:"クラス"%>
              <% end %>
             <% else %> 
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>